behaviors:
  base:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 200000
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 10000 #50000
    threaded: true
environment_parameters:
  levelDifficulty:
    curriculum:
      - name: firstLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420 # Number of episodes that have to exceed the defined threshold
          threshold: 2.5 # The defined threshold
        value: 0
      - name: secondLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420 
          threshold: 2.5
        value: 1
      - name: thirdLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 3
        value: 2
      - name: fourthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 3
        value: 3
      - name: fifthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 3
        value: 4
      - name: sixthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 3
        value: 5
      - name: seventhLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 4
        value: 6
      - name: eighthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 19
        value: 7
      - name: ninethLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 19
        value: 8
      - name: tenthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 19
        value: 9
      - name: eleventhLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 19
        value: 10
      - name: twelvthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: base
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 19
        value: 11